# -*- coding: utf-8 -*-
"""prob_solve.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fG4WoQaSKwY2rSMK1_2YJKtCUjPG4goM

# **“I’m not gonna run away, I never go back on my word! That’s my nindo: my ninja way.” – Naruto**
"""

#1.  given the length of any side find the area of an equilateral triangle.

# area of the equi triangle = ((sq root (3)/4)*(side)^2)

side = float(input("Enter the side of the traingle: "))
area = ((3**0.5)/4)*(side**2) # (3)^(1/2)
print(round(area,2))

#2. given an integer number n, return the difference between the product of it's even digits and sum of it's odd digits.

n = float(input("Enter the integer: "))
plus = 0 # bcz when i add 0 to any number it's value doesn't change
mult = 1 # bcz when i multiply any number with 1, it's value is not gonna change

while n>0:
  d = n%10

  if n%2==0:
    mult = mult*d
  else:
    plus = plus + d

  n = n//10
print(mult-plus)

odd = 1,3,5,9 = 18
even = 4,2,4 = 32
diff = 32-18 = 14

1424359//10

1424359/10

#3. Take input from the user in one line and the output should be a list

n = [float(i) for i in input("Enter the number: ").split(",")]
print(n)

#4. jack can go out with his friends only on the even days of a given month. write a program to count the number of days he can
    # go out in the month of august.

n = str(input("Enter the full name of the month: "))

if n=='February':
  y = int(input("Enter the year: "))
  d = int(input("Enter the number of days of the month: "))

  if y%4==0 and y%100==0 and y%400==0:
    print("its a leap year and jack went out for ", d//2, "days")
  else:
    print("it's not a leap year and jack went out for ",d//2,"days")

elif n=='January' or n=='March' or n=='April' or n=='May' or n=='June' or n=='July' or n=='August' or n=='September' or n=='October' or n=='November' or n=='December':
  a = int(input("Enter the number of total days in a month: "))
  print("Jack went out for ",a//2,"days")
else:
  print("Provide the valid month!")

leap year : no divisible by 4, 100, 400

#5. write a program to print the sum of negative numbers, sum of positive even numbers and sum of positive odd numbers from
    # a list of numbres (N) entered by a user. The list should terminate when a user enters a zero.

n = int(input("Enter the number of elements in the list: "))
y = []
for i in range(0,n):
  a = int(input("enter the element: "))
  y.append(a)

sum1 = 0
sum2 = 0
sum3 = 0

for i in y:
  if i>0:
    if i%2==0:
      sum1 = sum1 + i
    else:
      sum2 = sum2 + i
  elif i<0:
    sum3 = sum3+i
  else:
    break
    y.append(i)
print("sum of the positive even nos: ", sum1)
print("sum of the positive odd nos: ", sum2)
print("sum of the negative nos: ", sum3)

52,4,6,8,10,12,14,16,18,20,22,24,26,28,30

[1,8,9,6,5]
negative numbers = 0 # won't be any sumn bcz only a single number
positive even numbers = 8,6 #8+6=14
positive odd numbers = 1,9,5 #1+9+5= 15

1%2

1%2

